### PR TITLE
62 add support for ARRL DX Contest

### LINKED ISSUE #62: Add support for ARRL DX Contest
## Contest information

* **Contest Name:** ARRL DX Contest
* **Contest Rules:** https://www.arrl.org/arrl-dx
* **Call History file name:** [ARRLDXCW_USDX.txt](https://n1mmwp.hamdocs.com/mmfiles/arrldxcw_usdx-txt-2/)

### Unique contest behaviors

* Contest exchange: W/VE stations send a signal report and their state or province. (See the [ARRL Contest Multipliers List ](http://contests.arrl.org/contestmultipliers.php) for a list of abbreviations.) DX stations send a signal report and power as a number or abbreviation.

### Additional information

* It would be nice if user could pick DX-side or US-side for this contest. Perhaps with a checkbox, or two call history files, one for DX and one for US. Or, a checkbox in a setting dialog (which we don't have yet).

### Can you help?
Please let us know if you are available to help. (replace '[ ]' with '[x]' to affirm)
- [x] Yes, I'm available to discuss questions or alternatives regarding the implementation of this contest.
- [x] Yes, I'd like to review and provide feedback on the proposed solution.
- [ ] Yes, I'm available to help test this contest. Let me know when it is ready for early testing.

### PR DESCRIPTION
**Pull request by w7sst**
Fixes #62. Implements ARRL DX Contest. Introduces TDualExchangeContest as a base class to provide common behaviors to contests with variable exchanges between callers.

### CODE REVIEW

**Comment by w7sst** [comment]
If you want to test this, here is a link to a zip file containing the latest build. https://nextcloud.brashlerphoto.com/s/MicQNZdFNcsk6zq

**Review by ct7aup — APPROVED** [review]

**Review by Yagi-Berra — COMMENTED** [review]
This is wonderful!  The timing couldn't be better. I look forward to practicing ahead of ARRL DX next February.  A couple of comments:

re Power variations: I looked at my Cabrillo from last year's contest.  I always record exactly what was sent and never convert.   Program handles K, KW, 1TT, 5TT.  My log also shows A00, Aoo, ATT.  and NN.  Program does not accept these, but should.  Also non-US/VE stations should occasionally send A00, Aoo, ATT,  and NN in addition to the common K, KW, 1TT, 5TT variations.

If the home call is a USA call and I enter the power sent to me as 1TT in the lower left Power field, it automatically converts the power to 100.  Some contesters agree with me and enter what was sent while others do mental conversions and enter the numerical equivalent. I think the Power field should do no conversions visible to the user.  The program should accept either 1TT or 100 as valid entries.

**Comment by f6fvy** [comment]
In the same vein concerning abbreviations, allow ENN to be sent instead of 5NN like several do in real life would be useful. For now, it's rejected (red error message). And apply it to the DX stations randomly as well.

**Comment by w7sst** [comment]
> In the same vein concerning abbreviations, allow ENN to be sent instead of 5NN like several do in real life would be useful. For now, it's rejected (red error message). And apply it to the DX stations randomly as well.

And again I learn something new. I had now idea that ENN is used as a cut-version of 5NN/599. Yes, I can add this for both the user and the sending stations. I will include this in my next drop.

**Comment by w7sst** [comment]
Hi Larry,
Is it true that using ENN only applies to sending a cut RST field and NOT age, power or serial number? Will contesters ever send eTT for 500 watts? Or 1e0e for a serial number 1505?

I am assuming this is for RST only.

When adding the 599 conversion to ENN, MR will cut 10% of the 599 signal reports to ENN. This is to say, some of the sending stations will use the ENN cut form, not all of them. If you think this percentage number should be different, please let me know. 

Thank you for the clarification.

@f6fvy @Yagi-Berra

**Comment by f6fvy** [comment]
> I am assuming this is for RST only.

It is extremely rare to use it for anything else than 5NN. Stick to the RST only and it will be fine.

> When adding the 599 conversion to ENN, MR will cut 10% of the 599 signal reports to ENN.

5% seems more realistic to me.

Tnx for this modification. It can wait the next version if you want. No hurry ;-)

**Comment by f6fvy** [comment]
Don't modify the entered field. Just send ENN instead of 5NN and if will be fine.

**Comment by Yagi-Berra** [comment]
>> BTW, regarding the cut numbers in exchanges, all seasoned contesters do mental conversion and always enter the exchange as numbers, mostly because they use the keypad.

Yes, *some* top contesters convert 1TT to 100, but not *all.*  MRCE should accommodate both styles of log entry.

**Comment by w7sst** [comment]
@f6fvy @Yagi-Berra -- The cut-number support as discussed above will be implemented as part of Issue #145. This change will include sending ENN for RST value.

**Comment by nh6o** [comment]
I just discovered MRCE this week, and tested the ARRL DX contest with my Hawaii callsign. The program wouldn't accept a power exchange - KH6/KL7 are DX stations in that contest.

**Pull request merged**
