### PR TITLE
ARRL DX: accept 1TT or 100 as valid power entries

### LINKED ISSUE #145: MR should accept 1TT or 100 as valid power entries
## Summary
@Yagi-Berra reported [this feedback](https://github.com/w7sst/MorseRunner/pull/138) during initial testing of ARRL DX Contest...
> re Power variations: I looked at my Cabrillo from last year's contest. I always record exactly what was sent and never convert. Program handles K, KW, 1TT, 5TT. My log also shows A00, Aoo, ATT. and NN. Program does not accept these, but should. Also non-US/VE stations should occasionally send A00, Aoo, ATT, and NN in addition to the common K, KW, 1TT, 5TT variations.

> If the home call is a USA call and I enter the power sent to me as 1TT in the lower left Power field, it automatically converts the power to 100. Some contesters agree with me and enter what was sent while others do mental conversions and enter the numerical equivalent. I think the Power field should do no conversions visible to the user. The program should accept either 1TT or 100 as valid entries.

## Motivation
As described above, contesters would like to enter what they hear.

## Detailed Description
MR should allow users to enter what they hear when recording power fields. This means when checking the log entry, the values must be converted to the equivalent numeric value and compared against the expected value.

## Can you help?
Please let us know if you are available to help. (replace '[ ]' with '[x]' to affirm)
- [x] Yes, @Yagi-Berra is available to discuss possible solutions and alternatives to this problem.
- [x] Yes, I'd like to review and provide feedback on the proposed solution.
- [x] Yes, I'm available to help test a solution to this problem.

### PR DESCRIPTION
**Pull request by w7sst**
- allow cut numbers to be supported as power entries
- user is able to log what they hear
- display logged exchange value in screen log
- fixes #145

### CODE REVIEW

**Review by K6OK — APPROVED** [review]
Later on when user-supplied Cabrillo history files are supported, then TrueExch2 might be 1TT or ATT instead of 100, depending on what file they use.   ARRLDXCW_USDX.txt only has 100 and no cut numbers.  Might need to do this?

701  etPower:       if ReducePowerStr(TrueExch2) <> ReducePowerStr(Exch2) then Err := 'PWR';

**Review by K6OK — APPROVED** [review]

**Comment by w7sst** [comment]
Thank you for testing both domestic and DX sides of this contest. I appreciate it.

1. I updated regular expressions for ATT, Aoo, A00 or NN. Also allow them to be entered into exchange fields. This regex is now: `'([0-9]*)|(K)|(KW)|([0-9A]*[OTN]*)'`.
2. For the domestic runner case above, I did changed the regular expression for states/provinces to expect two characters making up US state or VE province: `'[ABCDFGHIKLMNOPQRSTUVWY][ABCDEFHIJKLMNORSTUVXYZ]'`. This will reject the 'K' or the 'KW' and accept any valid state or province.

I posted an [updated build](https://nextcloud.brashlerphoto.com/s/MicQNZdFNcsk6zq) for further testing.

**Comment by w7sst** [comment]
This regular expression is used for validating the user's Sent Exchange (Edit4 near the Contest Selection dropdown in the upper right corner). This is not used to validate incoming values from a history file or future Cabrillo file. Also, MR has always restricted some restrictions on the characters when entering data into the received exchange values.

I sometimes question whether this error checking on the Sent Exchange string(s) is necessary or not. Perhaps this should be backed off and treated as a warning. After all, this check is what the simulator is sending back to the virtual Dx Stations and is not what is being sent to the user to be copied during the simulation. And perhaps that is your point - let the user send what they want (similar to log what you hear).

I notice that N1MM will restrict what is entered in the received exchange fields for ARRLDX Contest. For the domestic runner (running as w7sst), I must enter a valid Power level and for the DX Runner (running as f6/w7sst) a valid state/prov must be entered before the QSO is accepted. So perhaps all data from imported from a history or future Cabrillo file should be validated before usage during the simulation.

I can certainly change this back to expect any two character sequence for state/province.

**Comment by K6OK** [comment]
>> Perhaps this should be backed off and treated as a warning.

Sure.  I see data validation for the Edit4 textbox as a courtesy to the user that they might be making a mistake.

**Comment by w7sst** [comment]
> Perhaps this should be backed off and treated as a warning.

Looking at the code, I think I'll leave it as is. This regular expression is sometimes checking for all numeric characters to allow those characters to be stored in a numeric field (e.g. member numbers, age, etc.). Since we still use numeric values to store some of these fields, we should leave this in place. I think we can leave this as is for now and not make further changes.

**Review by ct7aup — APPROVED** [review]

**Pull request merged**
