### PR TITLE
errors in ARRL DXCC ARRL.LIST file (Coded by W7SST)

### LINKED ISSUE #147: Fix memory leak in CWOPS CWT file history reader
### Description
When the CWT history file is processed, a new `TCWOPSRec` object is allocated within a while loop. However, some records are ignored and a `continue` occurs. The object is reallocated.

### Steps To Reproduce
Can be seen via code review or in the debugger.

#### Expected behavior
No memory leak.

#### Actual Behavior
We drop objects.

#### Reproduces how often
100%

### Version information

  - Morse Runner version: latest
  - OS/Version: Windows 11

### LINKED ISSUE #149: fix errors in ARRL DXCC ARRL.LIST file
### Description
The ARRL.LIST file contains several errors and is out of date with latest from ARRL.

### Steps To Reproduce
Found problem with visual inspection and manual compare against latest file from ARRL.

#### Expected behavior
This file is used to determine which DXCC region a given callsign or callsign prefix resides.

#### Actual Behavior
Works okay for now.

### Version information

  - Morse Runner version: 1.81]
  - OS/Version: Windows 11

### Additional context
@f6fvy has recommended that we use the `wl_cty.dat` file. I agree and will submit a separate feature request for this item.

### PR DESCRIPTION
**Pull request by w7sst**
- updated to March 2022 edition
- https://www.arrl.org/files/file/DXCC/2022_DXCC_Current.pdf
- Z6 was missing
- many entries had incorrect regular expression values
- fixes #149

### CODE REVIEW

**Review by K6OK — COMMENTED** [review]
Note that CQWW and CQWPX entity list uses the ARRL DXCC list but also adds IG9 (African Italy – Lampedusa) and IH9 (African Italy – Pantelleria) as separate entities for multipliers.  ARRL contests lump IG9 and IH9 as "I" Italy.

**Comment by f6fvy** [comment]
There are also

- IT9 Sicily (different from I  or IG9 previously mentioned)
- 4U1V
- TA/Asia is a different mult from TA1/Europe
- JW/b  (Bear Isl)
- GM/s (Shetland Isl)

All these entities are marked with a * before the prefix in the CTY files. It applies among others to the CQWW, CQWPX  and WAEDC contests.

**Comment by w7sst** [comment]
Well, I think we have a possible copyright problem with our use of the ARRL.LIST file. It appears that the DXCC List is copyrighted by ARRL and we may not be able to reproduce it here. The usage of ARRL.LIST and ARRL.pas was originally added by BG4FQD. We got this from @BH1SCW 's repository. I think they took the raw dxcc list information and inserted a regular expression column and added a REGEX search engine. This is what we are now using and have been building upon.

This statement is from the [ARRL DXCC Entities List page](http://www.arrl.org/country-lists-prefixes).
>This text file of all Current and Deleted entities is designed to be imported into various databases and spreadsheets. It is available for one's personal use. Please remember that DXCC is Copyrighted. ARRL permission is required for use of this list for other than one's personal use.

Here is original link where I learned about this problem.
- https://pypi.org/project/call-to-dxcc/

So what do you guys think? Do we have to back away from this? @f6fvy @K6OK @scotthibbs @BH1SCW @tekenny

### Options
- One option is to build the `cty` country file support as suggested by @f6fvy .
- Another short-term option is to pull the ARRL.LIST support and only implement the US/CA lookup as needed for ARRL DX Contest. We can do this while building out the `cty` country file support.

### Question
Do we have access to any `cty` country file reader source code? @f6fvy , do you have any code that supports this in WinTest (I think you said you are working on this). If so, we could port it to FPC.
@f6fvy

**Comment by K6OK** [comment]
3rd option: Ask ARRL for permission.  Since MRCE is open source, not-for-profit software I think there's a good chance they will say yes.  Would you like for me to contact them?

**Comment by w7sst** [comment]
> 3rd option: Ask ARRL for permission. Since MRCE is open source, not-for-profit software I think there's a good chance they will say yes. Would you like for me to contact them?

Yes, please contact them. Good suggestion. Thank you.

**Comment by f6fvy** [comment]
IMHO, relying on the CTY file is a much better solution : They're maintained (almost) on a daily basis, and used by dozens of loggers or contest loggers.. AD1C does this job for years. And they fit for all situations (like the CQWW, CQWPX  and WAEDC exceptions).

**Comment by K6OK** [comment]
F6FVY >> IMHO, relying on the CTY file is a much better solution

CTY.DAT is [copyrighted ](https://www.country-files.com/copyright/) also -- but his license is broad anyone can use his files.

On further thought, I agree with you.  An example is DXpedition K8H.  If someone makes their own call history file from public Cabrillo logs (like I do) and K8H is in there, AD1C's CTY.DAT will correctly assign that call to American Samoa (KH8) while ARRL.LIST will classify it as USA (K8).

The only drawback with using CTY.DAT is that it comes at the price of additional coding complexity.  Every callsign will have to be searched against the many =call exceptions.  Plus coding to deal with *IG9, *1H, etc non-ARRL prefixes.  ARRL.LIST is a much simpler solution but it is not as accurate.

**Comment by f6fvy** [comment]
Dealing with the * entities sounds not really complicated. You can skip them (or not) when parsing the file. And put all =callsign exceptions in some sort of map. Just my 2 cents.

**Comment by scotthibbs** [comment]
We will definitely need permission from the ARRL if we include the file in our release because we will then be publishing it. 

Solution 1: Since it is free for personal use, the "call-to-dxcc" solution was having his software download it from the ARRL. We can do that.

Solution 2: Wait for permission from ARRL

Solution 3: We can avoid copyright by modifying the ARRL list into our own format. As the "call-to-dxcc" project notes, the list has flaws anyway. So if we reorder the list into our own format, all good. (this is done with the ARRL repeater directory "You can reproduce information from the Repeater Directory on your website, but you cannot do it in the same format as a Repeater Directory page. The same applies to factual information you may find in other ARRL publications" 

Solution 4: Use Amateur Radio Country Files by Jim Reisert AD1C. His copyright is similar to ours. It is not restrictive because his copyright already gives us permission. (including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so.)

One of my (python) repositories uses the cty.dat file to parse a callsign into a prefix, separator, and suffix and also determine the country from the prefix. So if it's useful...

**Comment by w7sst** [comment]
This has been an interesting discussion. Let's keep in mind that the current usage of this DXCC information is currently very simple. There are two usages:
1. for ARRL DX Contest, the user's callsign is searched to determine if the callsign is US or Canada. This determines whether the user is on the domestic or DX side of this contest.
2. for the status bar information, the user's prefix is extracted and searched to find the user's entry in ARRL.LIST. Once found, the status information is displayed in the status bar for some contests.

So, the only accuracy needed for now is to determine if user's call is within US/CA for the ARRL DX Contest. In other words, the accuracy is not important - MR isn't doing DXCC qualifications. Subsequent contests, perhaps the ARRL 10m Contest will require better DXCC lookups because the station's exchange depends on their location. We might be able to use information from the N1MM call history file to deduce what exchange the Dx Station will be sending (thereby reducing our need for accurate DXCC lookup information).

As Scott pointed out, the format has already been changed and a new RegEx column was added by BG4FQD. The ARRL file is in a different format from the one BG4FQD created. We have modified this later file.

We can do further modification and drop all the '*', '#', and (nn) comments in the first column. These codes document:
- `*` - ARRL QSL Forwarding service provided
- `#` - US Amateurs may handle third-party traffic.
- `(nn)` - lots of footnotes. They are of no use to MR.

I will remote this extraneous information. Doing so plays to Scott's suggested Solution 3 since we are dropping much of their information and using a different format along with an additional column.

@K6OK offered to check with ARRL. Knowing we are using a different format may help - oh wait, Scott said we are publishing the file.

I feel better knowing that we are using a different format.

Thoughts?

**Comment by scotthibbs** [comment]
I didn't know we had a different format!!  We are golden. If so, we can edit further and remove all reference of the ARRL, including file name just to avoid confusion. 

I don't mind editing the file into a better format.. So if you have a format or need changes done to it that would seem extremely tedious, I'll be glad to tackle it. 

If you take me up on this, just create an issue with the format you wish to have (say add a us/can/dx column) or if you want it comma delimited or something. Just give me an example of a line of it and assign it to me.

**Comment by w7sst** [comment]
@scotthibbs - here is the link to the ARRL file: https://www.arrl.org/files/file/DXCC/2022_DXCC_Current.pdf

Sample from the ARRL file:
image

Here is a sample from our file:
```
March 2022 Edition
https://www.arrl.org/files/file/DXCC/2022_DXCC_Current.pdf

1A;1A;Sov. Mil. Order of Malta;EU;28;15;246
3A;3A;Monaco;EU;27;14;260
3B6,7;3B[6|7];Agalega & St. Brandon Is.;AF;53;39;004
3B8;3B8;Mauritius;AF;53;39;165
3B9;3B9;Rodriguez I.;AF;53;39;207
3C;3C;Equatorial Guinea;AF;47;36;049
3C0;3C0;Annobon I.;AF;52;36;195
3D2;3D2;Fiji/Conway Reef/Rotuma I.;OC;56;32;176
3DA;3DA;Swaziland;AF;57;38;468
3V;3V;Tunisia;AF;37;33;474
3W;3W;Viet Nam;AS;49;26;293
XV;XV;Viet Nam;AS;49;26;293
3X;3X;Guinea;AF;46;35;107
3Y;3Y;Bouvet;AF;67;38;024
```

**Comment by K6OK** [comment]
I sent the e-mail to ARRL about 5 hours ago, which means they have formal notice that we are using their file.  Merely removing footnotes or changing the filename is not going to shield MRCE from a copyright claim, if ARRL doesn't want us to use the data.  Let's wait to see what their response is.  I'm optimistic they will give permission.

I mentioned that MRCE is the same program they wrote about it in the Nov 9 _ARRL Contest Update._   I dropped that as a hint that in effect they have given implicit approval.  :-)   As soon as I hear back I'll share with the group.

**Comment by w7sst** [comment]
I will rename the file.

**Comment by K6OK** [comment]
> I will rename the file later tonight.

Why?  It serves no purpose.  If ARRL gives permission, then the name can stay the same.  If ARRL says no, then there is no choice except to use cty.dat.   I'll say it again: changing a file name or rearranging the data will not shield MRCE from a copyright claim.

I strongly advise everyone to stop and wait for ARRL's response.

**Comment by w7sst** [comment]
> I strongly advise everyone to stop and wait for ARRL's response.

Agreed.

**Comment by scotthibbs** [comment]
> I'll say it again: changing a file name or rearranging the data will not shield MRCE from a copyright claim. 

I hope you shared with them a copy of our .LIST file so they know it is not the identical PDF they sell for $5.95, to which applies their copyright. 

The factual information is not copyrighted (just like our phone number or address can be reprinted but we can't reprint the phone book page). Fair use doesn't apply because we are not quoting directly from the work, but saying it differently. Changing the name isn't to get out of a copyright claim (In this case we just remove it - no harm), it is to avoid confusion that we are republishing the actual PDF article that is being sold, or that this file belongs to the ARRL. 

Besides there are many sources for these DXCC entries, not just from ARRL. DXView (from DXLab Suite) has a DXCC mdb database we could use. It's overkill, but we could use this as a source as well to basically recreate the file. I'm sure they use the ARLL list as well but there is not one attribute to them in the database.  http://www.dxlabsuite.com/dxview/DXCC.exe 

I'm in agreement we wait for the ARRL, but we don't need to.

**Comment by K6OK** [comment]
@scotthibbs  -- There are three tests to determine a copyright violation in US courts:

1. Does the owner of the work exert copyright?  Yes, ARRL does.
2. Did the 2nd party obtain and use a copy of the work?  Yes, MRCE did.
3. Does the 2nd party's version constitute a "substantial similarity" to the original?  Yes, it does.

"Under the doctrine of substantial similarity, a work can be found to infringe copyright even if the wording of text has been changed or visual or audible elements are altered"  ([source](https://en.wikipedia.org/wiki/Substantial_similarity)).  This is why changing the filename or altering the data is not going to help.  

>>I hope you shared with them a copy of our .LIST file so they know it is not the identical PDF they sell for $5.95, to which applies their copyright.<<

I did.  However, note that ARRL limits the use of the digital file to "personal use" only.  We are going beyond personal use and will be making an unlimited redistribution of it.  We are acting as publishers, not personal users.  

Sorry if I seem argumentative on this issue.  I think that since everything we do here is open and transparent, it's important that we have everything in order in keeping with the Mozilla copyleft license.

**Comment by scotthibbs** [comment]
I don't mind the argument. I thank you for taking the time to disagree with me. In doing so I have learned a lot. 

However, as we should do more often in our society, we will have to respectfully disagree. 

The doctrine of substantial similarity wouldn't be raised yet. The ARRL publishes a list of countries for DXCC. The article itself is copyrighted (theirs has several paragraphs and a table format). It would be wrong of us to reproduce this article (even with a few things changed like removing the paragraph and using their table), however the ingredients of that list (the factual information or knowledge) is not subject to copyright. We are not using their wording or their table. We are using the ingredients of the list to make a text file readable by a program in a completely different format from their pdf article. 

"A mere listing of ingredients is not protected under copyright law." & "Copyright does not protect ideas, concepts, systems, or methods of doing something." (https://www.copyright.gov/help/faq/faq-protect.html#what_protect)
The ARRL's idea of a country for credit is not copyright. 

We should remove the footnotes because these would be protected, it could be considered a violation of copyright and we have done so. And we should change the ARRL name of the file, not because of copyright, but because of trademark. That and it suggests that the ARRL made the file we are using.  (this file was inserted by international hams not worried about copyright law at the time, not a product of ARRL) Now that we removed the name and the footnotes. We are golden. 

I really do appreciate the discussion. In doing so we are making the "community edition" a better program.

**Review by ct7aup — APPROVED** [review]

**Comment by K6OK** [comment]
@ scotthibbs >> We should remove the footnotes because these would be protected, it could be considered a violation of copyright ... Now that we removed the name and the footnotes. We are golden. <<

No disrespect intended but unless you're an attorney you can't say for sure.  Don't feel bad, I'm not a lawyer either so my opinion is even more worthless, LOL.  Once we get the ruling from ARRL we will have full clarity on the issue.  If I don't hear from them by Wednesday the 7th I'll call ARRL HQ and follow up.

**Comment by K6OK** [comment]
Good news -- per my phone call and e-mails with ARRL, permission is granted to use DXCC.LIST under two conditions --
1. MRCE does not market or imply our software is endorsed by ARRL.
2. ARRL requests that we add a header to the top of DXCC.LIST that says "Used with permission: DXCC Country List, copyright ARRL."

Now we don't have to change filenames, remove footnotes, rearrange data, etc. and we are free to use the file/data as we wish.

**Review by scotthibbs — COMMENTED** [review]
The file name should be changed to DXCC.LIST. This is not a copyright issue, it's to avoid the indication that this list is from and/or endorsed by the ARRL. (edit: ARRL is their trademark) I am glad they gave permission (if needed or not) so that further confusion can be avoided in the future.

**Comment by w7sst** [comment]
I will rename the file as suggested this evening and update the corresponding code.

**Comment by w7sst** [comment]
Strike that. I think I'll leave the file name as is for this release. We can change the file name next release.

**Pull request merged**
