### PR TITLE
change MR defaults to match Alex in Ontario for all contests

### PR DESCRIPTION
**Pull request by w7sst**
- change default values to match Alex's QTH in Ontario
- ARRL/RAC section default is GTA
- reduce initial CW speed down to 25 wpm
- disable all Band Condition checkboxes
- disable QSK checkbox

### CODE REVIEW

**Comment by w7sst** [comment]
I updated the [latest build](https://nextcloud.brashlerphoto.com/s/MicQNZdFNcsk6zq).

**Comment by w7sst** [comment]
I changed Alex's ARRL/RAC section default to GTA (used in ARRL Field Day Contest).

**Comment by K6OK** [comment]
Almost there -- QSK is checked on initial startup.

**Comment by w7sst** [comment]
Good catch. I updated the [latest build](https://nextcloud.brashlerphoto.com/s/MicQNZdFNcsk6zq). @K6OK

**Review by K6OK — APPROVED** [review]

**Pull request merged**
