### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by w7sst**
I updated our roadmap for next year. Please let me know if you have any additional input or changes you would like to propose. I'd like to update the roadmap prior to the v1.82 release.

thank you,
Mike w7sst

### CODE REVIEW

**Review by K6OK — COMMENTED** [review]
A couple of thoughts:

* Propose that adding the IARU HF Championship contest (July) be made a priority (Spring 23?).  It has high global participation with 4,000 logs last year.  I believe adding it will improve MRCE's appeal internationally.  I didn't add it to the roadmap because I'm not sure if the team agrees or is comfortable promising it?
* Suggest saying the team will evaluate the GUI for ergonomic enhancements.
* Any thought to localization/internationalization to support other languages?

**Comment by w7sst** [comment]
@tekenny - I made a few edits to DEVELOPERS.md and added it to this PR branch.

**Comment by w7sst** [comment]
> * Propose that adding the IARU HF Championship contest (July) be made a priority (Spring 23?).  It has high global participation with 4,000 logs last year.  I believe adding it will improve MRCE's appeal internationally.  I didn't add it to the roadmap because I'm not sure if the team agrees or is comfortable promising it?
> * Suggest saying the team will evaluate the GUI for ergonomic enhancements.
> * Any thought to localization/internationalization to support other languages?

I like the idea of the IARU HF Championship contest (I even participated in that contest last summer too, had fun). Anyway, yes, that is a good suggestion. Let me look at the rules and see if it fits our current pattern. If it does, I'll update the roadmap. **Please** add this as a new Issue (contest request).

I have thought about localization, but do not have the expertise in Delphi to pull it off. **Please** add this as a new Issue (feature request) and we'll look/wait for some people to help.

**Review by scotthibbs — APPROVED** [review]
Nice work!

**Review by scotthibbs — APPROVED** [review]

**Comment by w7sst** [comment]
@tekenny - Hi Tom, do you have time to look at the changes I made referencing your `DEVELOPERS.md` file changes? I wanted to see if you had any input. thanks, Mike

**Review by ct7aup — APPROVED** [review]

**Pull request merged**
