### PR TITLE
Introduce class hierarchy to support common Contest behaviors

### PR DESCRIPTION
**Pull request by w7sst**
Implements a common class hierarchy to support contests. contest-specific behaviors will be implemented in the various derived contests. See Issue #124 for a UML Class Diagram showing this hierarchy. This refactoring introduces the base TContest class along with 5 derived subclasses.

### CODE REVIEW

**Review by jr8ppg — APPROVED** [review]
GetCall and PickStation methods in TContest class should be abstract

**Comment by w7sst** [comment]
> GetCall and PickStation methods in TContest class should be abstract

thank you! I was wanting to do that, but could not find the keyword.

**Comment by tekenny** [comment]
The code looks good to me but I'm still a newbie here :-)

Conceptually the abstraction seems good.
A couple of questions/suggestions:
1 - Rather than have a Pascal file for each contest could we have a config file for each contest to make it more data driven?
2 - I wonder if there is any way we can reuse N1MM Logger contest config files. If so that could make supporting contests allot easier.
Finally, I think this PR can be merged and the above 2 thoughts might just be considered for future enhancements assuming they are applicable and possible.

**Comment by w7sst** [comment]
> The code looks good to me but I'm still a newbie here :-)
> 
> Conceptually the abstraction seems good. A couple of questions/suggestions: 1 - Rather than have a Pascal file for each contest could we have a config file for each contest to make it more data driven? 2 - I wonder if there is any way we can reuse N1MM Logger contest config files. If so that could make supporting contests allot easier. Finally, I think this PR can be merged and the above 2 thoughts might just be considered for future enhancements assuming they are applicable and possible.

I agree with your suggestions. Initially, the contests where all table driven with lots of switch statements. This class hierarchy removes the switch/case statements, but we still have lots of classes, one for each contest. I agree that additional table-driven techniques could be used as we identify common behaviors across contests. The tricky part I'm focusing on now is dynamic exchange types where the exchange changes by contest. I missed this during my initial design and am reworking my approach now.

To your second idea, yes, N1MM does have the UDC (User-defined contests) - that would be cool to perhaps support those someday.

I've been working with Steve, N2IC, on N1MM integration - I'm hoping that this multi-contest version can work with N1MM so N1MM can be used to enter contest data with MR generating the sounds.

**Comment by w7sst** [comment]
I discovered another issue with the above code. The FD, Wpx, WW, CWOPTS, and NaQP contests only need to read their call history files one time. Only the future ARRL DX Contest will require reloading if the user's callsign changes (part of a future integration).

**Pull request merged**
