### PR TITLE
add contest-specific scoring

### LINKED ISSUE #139: Contest-specific scoring rules are not implemented
### Description
It turns out that contest-specific scoring has not been implemented for any of the contests.

### Steps To Reproduce
1. Run CQ WW Contest
2. Log a few QSOs
3. The scoring table in the lower right of the screen is not correct.

#### Expected behavior
Contest scoring rules should be implemented.

#### Actual Behavior
Currently, CQ WPX contest rules are implemented for all contests.

#### Reproduces how often
100%

### Version information
  - Morse Runner version: 1.81
  - OS/Version: Windows 11

### Additional context
Please see the discussion [How important is exact contest scoring in MRCE](https://github.com/w7sst/MorseRunner/discussions/137).

### PR DESCRIPTION
**Pull request by w7sst**
Fixes #139 - adds Contest-specific scoring to MRCE.

Please see #137 discussion for more information.

### CODE REVIEW

**Comment by w7sst** [comment]
If you want to test this, here is a link to a zip file containing the latest build. https://nextcloud.brashlerphoto.com/s/MicQNZdFNcsk6zq

**Review by ct7aup — APPROVED** [review]

**Review by Yagi-Berra — COMMENTED** [review]
From what I was able to test, the simplified contest scoring is fine.  Ideally CQ WW should show Zones and Countries instead of Mult, but that's a minor enhancement.

Unlike the other contests, WPX does not use a plaintext call history file?  Is it using MASTER.DTA?  For CQ WW I substituted my own CQWWCW.txt with call history from local stations so that it would reflect what I'd hear on the air.  I'd like to do the same with WPX.  If it's using MASTER.DTA I can't edit it as it is a binary file.

I could not test WPX scoring because it takes too long for the same prefix to appear a second time, which is needed to see if it correctly gives 0 mult credit for the 2nd prefix instance.  I looked at the code and it appears to handle it correctly.

**Comment by f6fvy** [comment]
> If it's using MASTER.DTA I can't edit it as it is a binary file.

You can use MEdit (from VE3NEA as well) http://www.dxatlas.com/MEdit/

**Comment by Yagi-Berra** [comment]
> > If it's using MASTER.DTA I can't edit it as it is a binary file.
> 
> You can use MEdit (from VE3NEA as well) http://www.dxatlas.com/MEdit/

Never heard of MEdit. Thank you for sharing the link.

**Review by ct7aup — APPROVED** [review]

**Comment by w7sst** [comment]
I moved the above conversation into Issue #146 - Add optional call history file to CQ Wpx Contest.

**Pull request merged**
