### PR TITLE
Add IARU call history file

### PR DESCRIPTION
**Pull request by K6OK**
Upload call history file from 2021 public logs

### CODE REVIEW

**Comment by w7sst** [comment]
@K6OK - I changed the merge base to my `iaru-hf-contest` branch. This branch will also let you run the IARU HF Contest.

**Comment by K6OK** [comment]
>> That was fast.

Not hard with a spreadsheet and Notepad++  :-)

>> I'm wondering if we should increase the percentage of IARU-related callsigns

Thinking about this from a big picture standpoint, I think the simplest and most straightforward policy should be all call history files should be unaltered derivations from public logs.  I did this by selecting top score logs from NA, EU and JA, merging them then removing duplicates.  It's a global-neutral approach.  Keeps it simple for maintainers in the years ahead.

I learned from CQ WW that the only way to get a fully accurate simulation of what I'm going to hear is by making a custom CH file from nearby public logs.   What West NA hears is very different from East NA, EU, JA, VK, etc.   Even within EU what EA hears is different than what SM hears.  Due to this wide-ranging regional variability I think we need to put it on the advanced user to make up their own CH files if they want to.  Too many variations of regions and contests for us to manage it.  

Later on consider supporting a Settings dialog that allows the user to swap CH files along with help documentation that describes the format and how to do it.  If we end up supporting that we shouldn't alter the callsign mix in the program as that will interfere with the user's custom CH mixes.    -- Jim K6OK

**Comment by w7sst** [comment]
I like the idea of selectable history files. I like your approach of combining the top logs from the different regions. Perhaps we can merge in the list (or append it at the end with a separate title and remove duplicates). This will capture all known Society calls and still capture the global merge top-call logs.

**Comment by w7sst** [comment]
We could also provide additional a directory of additional files (perhaps by region `IARU_HF_NA.txt`, `IARU_HF_JA.txt`, `IARU_HF_EU.txt`, `IARU_HF_SOCIETY_ONLY.txt`, etc.) and provide instructions for updating the `IARU_HF.txt` file in the main runtime directory. This will allow users to copy in the file they want to use. We could do this until we get the Settings Dialog in place.

I think for now I'd like to append the society file to the end of your file with a clear comment of what I have done. I'll update the reader to remove any duplicates (which may be good anyway in case users are modifying their own files).

**Comment by K6OK** [comment]
OK -- sounds good!  I ran IARU to do some cursory checking, seems to run fine.

**Pull request merged**
